### ISSUE TITLE
unsymetrical workspace switcher

### ISSUE THREAD

**Issue by rcmz** [ZorinOS/zorin-desktop-themes#14]
The gnome 40 workspace switcher has rounded corners on the left and straight corners on the right, which looks ugly 🤓

<img src="https://i.imgur.com/kGMtwpf.png"/>

**Comment by ArtyomZorin** [comment]
The Zorin gnome-shell themes aren't designed to work with GNOME Shell 40+ yet. Will fix during the development cycle for the next version of Zorin OS.

**Comment by ArtyomZorin** [comment]
Support for GNOME Shell 40+ is now added in the new 4.0 release, so this bug is fixed.
