### ISSUE TITLE
[FEEDBACK] Add a top pane to the desktop with the global menu

### ISSUE THREAD

**Issue by mathpfvr** [ZorinOS/zorin-desktop-themes#2]
A very interesting and welcome visual feature would be a top panel with the global menu

Unity 7
![00_global_menu](https://user-images.githubusercontent.com/7264001/61584872-dfe55880-ab25-11e9-889b-fcfc673ff4f8.png)

KDE 
![Screenshot_20190329_034608](https://user-images.githubusercontent.com/7264001/61584877-e4117600-ab25-11e9-8795-52e3e3dc1d97.png)

MATE
![vala-panel-topmenu-ubuntu-mate](https://user-images.githubusercontent.com/7264001/61584879-e83d9380-ab25-11e9-8377-a946a3f41e04.png)

**Comment by ArtyomZorin** [comment]
This isn't controlled by the theme, but rather Gnome Shell. If this functionality is to be added, a Gnome Shell extension and app integration would need to be developed.
