### ISSUE TITLE
Brother DCP-T310 Printer :: Stopped Working After The Latest Updates

### ISSUE THREAD

**Issue by webmaster85** [ZorinOS/zorin-desktop-themes#20]
The printer suddenly stopped working after the latest updates. The scanner and copier work fine, and so is the printer if I connect it to a Windows OS.

**Comment by ArtyomZorin** [comment]
Closing as this issue isn't related to the Zorin desktop themes.

For support requests like yours, please visit the Forum: https://forum.zorin.com/
