### ISSUE TITLE
Chrome GTK+ theme flickering bookmark bottom issue.

### ISSUE THREAD

**Issue by roxshivamsingh** [ZorinOS/zorin-desktop-themes#23]
I pay yesterday for Pro version in 3639 INR. I think for good linux experience. Firstly after install OS I install chrome from deb extension I facing this issue when I select gtk+ theme.
I feel disappointment to pay money from my pocket money.

https://user-images.githubusercontent.com/56290347/177619507-717d2713-0dee-4139-91a5-267e52369bbc.mp4

![image](https://user-images.githubusercontent.com/56290347/177620082-2f93941b-513b-4fe5-970a-8da74733b3b2.png)
![Screenshot from 2022-07-07 00-09-51](https://user-images.githubusercontent.com/56290347/177620350-81e5c2d6-d8ad-415e-80fb-fa8635683fb7.png)

**Comment by roxshivamsingh** [comment]
![Screenshot from 2022-07-07 00-12-15](https://user-images.githubusercontent.com/56290347/177620690-ef45f91d-fadc-485a-8d9b-dbdf8011674d.png)

**Comment by ArtyomZorin** [comment]
Thanks for letting us know about this issue. We've now fixed this bug, so the bottom border of the main toolbar in Google Chrome/Chromium shouldn't flicker anymore.

You can get this fix by opening the Zorin menu > searching & opening the "Software Updater" and installing the latest software updates.
After the installation completes, please close Google Chrome and open it again to apply the fix.

**Comment by roxshivamsingh** [comment]
It update comes today. Thanks to fix this.
