### ISSUE TITLE
open tab in dark theme

### ISSUE THREAD

**Issue by rodrigoGA** [ZorinOS/zorin-desktop-themes#24]
In some apps like google chrome it is very difficult to find the open tab when using dark theme. 
I think it would be much better if a different background color is used for the active tab.

I would like to be able to edit the theme, but I don't know how to compile it. I appreciate if you tell me how to generate the theme from the source code so I can contribute

I think the property to change is `.background.chromium`

**Comment by ArtyomZorin** [comment]
Unfortunately we weren't able to replicate this issue ourselves. If you've updated to the latest version of Google Chrome and the zorin-desktop-themes package and are still experiencing this issue, could you please attach a screenshot of Google Chrome with one of the dark variants of the Zorin themes enabled so we could identify the issue?

**Comment by rodrigoGA** [comment]
zorin-desktop-themes:
![Captura de pantalla de 2022-08-02 15-37-54](https://user-images.githubusercontent.com/2334523/182449172-c76d5c59-b049-4824-92f2-1f846aefbdf4.png)

theme that uses different color for active tab, like the request suggestion:
![Captura de pantalla de 2022-08-02 15-38-46](https://user-images.githubusercontent.com/2334523/182449420-a59086ae-314c-4d98-b35d-d070a6eba976.png)

when working with many tabs it becomes difficult to find the active tab.
It would also be interesting to be able to collaborate, so if you want to share the source code or build instructions it would be very helpful.

**Comment by ArtyomZorin** [comment]
We've just published an update which makes the active tab colour different from the browser header's background to make it more visible. This is what it looks like with a dark theme:
![Screenshot from 2022-09-19 18-51-14](https://user-images.githubusercontent.com/3945334/191082203-94bfc373-c40d-4eaa-bc7c-9ae3544004bc.png)
