### ISSUE TITLE
Sometime I battery indicator shows wrong value.

### ISSUE THREAD

**Issue by roxshivamsingh** [ZorinOS/zorin-desktop-themes#25]
I am a premium user.

Sometime, I start my laptop battery indicator show low battery type icon. I don't know why but I paste some screenshots here.

![2022-07-22_12-02](https://user-images.githubusercontent.com/56290347/180387447-1721bbc2-3b7d-4a56-9106-15beab415b1e.png)
![2022-07-22_12-01_1](https://user-images.githubusercontent.com/56290347/180387455-7dc62147-d303-472c-a3a3-3b06c3482247.png)
![2022-07-22_12-01](https://user-images.githubusercontent.com/56290347/180387456-ba2276c1-c978-4150-99be-1c00b96b7313.png)

After I reboot properly, It shows right value in battery indicator. I paste screenshot here below.

![2022-07-22_12-05_1](https://user-images.githubusercontent.com/56290347/180387713-09ae3995-f4a5-48ee-9dad-6d2c4aa73660.png)
![2022-07-22_12-05](https://user-images.githubusercontent.com/56290347/180387722-49fc8dfc-fe48-4a77-977b-ffebfdd1ff9c.png)

You can compare screenshots according to timestamp. In zorin pro, nothing seems like premium or pro. It also contains UI glitches and bugs similar as ubuntu..

**Comment by ArtyomZorin** [comment]
This appears to be an issue with the battery level detection software for your specific computer model, and not the desktop themes (closing this GitHub Issue as a result).

We would recommend you to install the latest updates from the Software Updater. This will make sure you're running the most stable and compatible software for your computer.

For technical support queries, we would recommend you to contact our support team at https://zorin.com/os/zorin-installation-support/
