### ISSUE TITLE
Shell theme has padding issues with ArcMenu

### ISSUE THREAD

**Issue by UrkiMimi** [ZorinOS/zorin-desktop-themes#28]
![image](https://user-images.githubusercontent.com/74517821/188179129-91e48b41-d659-4878-b04c-2211a057c8cb.png)
Most of these issues happen with ArcMenu and causes some of the padding to not work properly at all. As a result this ends up happening since the padding is bugged. This happens on Ubuntu 22.04 with Gnome 42. I'll try it on other distros later today.

**Comment by ArtyomZorin** [comment]
The current version of the zorin-desktop-themes are designed for use in Zorin OS 16, which uses GNOME Shell 3.38. They will be updated to work with newer version of GNOME Shell closer to the release of Zorin OS 17 in mid-2023, which should fix this issue.
