### ISSUE TITLE
[FEEDBACK] Highlight colors and white and dark theme support in the dock

### ISSUE THREAD

**Issue by mathpfvr** [ZorinOS/zorin-desktop-themes#3]
The dock could have an option to choose between the dark and white theme, plus an option to choose a highlight color (orange, blue, or green adapt to the color of the wallpaper)

**Comment by ArtyomZorin** [comment]
The dock in Zorin OS already changes its appearance based on the set Gnome Shell theme. The theme can be set in Zorin Appearance > Themes.
