### ISSUE TITLE
Suggestion use Colloid theme as default

### ISSUE THREAD

**Issue by luisrguerra** [ZorinOS/zorin-desktop-themes#32]
I really like the Zorin OS GTK theme, but one of the few themes that beats the Zorin OS theme is [Colloid](https://www.gnome-look.org/p/1661959), it works wonderfully in many interfaces and already supports GTK 4. Implementing GTK 4 support must be a difficult task, I think that it would be interesting to start basing the Zorin OS theme on Colloid and make the necessary modifications.

![32e8128b807d2c2d3f57112eaba184a77ee1da3499b7bcbdb189ffc70572195d7aa7](https://user-images.githubusercontent.com/31783838/236588871-2c62f1dd-bbc4-4059-aeee-5a40424dfb91.png)

**Comment by ArtyomZorin** [comment]
Support for Gtk 4 is now added in the new 4.0 release of the Zorin theme, which also has a refreshed design.
