### ISSUE TITLE
Gnome-shell submenus issue with ZorinBlue-Dark

### ISSUE THREAD

**Issue by Odizinne** [ZorinOS/zorin-desktop-themes#36]
![image](https://github.com/ZorinOS/zorin-desktop-themes/assets/102679854/b2bf6224-d5ed-4cc5-bc2b-75272afc85f1)

The font is using the same color as the background.

Same issue might occur with other dark color variant.

Cloned from master

Tested on gnome-shell 42

This can be fixed by defining a color for the menu items.

`.popup-sub-menu .popup-menu-item { color: #2e393e; border-radius: 0; margin: 0; }`

![image](https://github.com/ZorinOS/zorin-desktop-themes/assets/102679854/64031ced-5696-447f-8edd-bf11a317d4c0)

This also need to be updated on hover

`.popup-sub-menu .popup-menu-item:focus, .popup-sub-menu .popup-menu-item:hover { color: #bde6fb !important; background-color: #2e393e !important; }`

**Comment by ArtyomZorin** [comment]
Thanks for reporting this issue! It should now be fixed in version 4.0.6.
