### ISSUE TITLE
Quick settings button are broken

### ISSUE THREAD

**Issue by Odizinne** [ZorinOS/zorin-desktop-themes#37]
![Screenshot from 2023-11-20 13-40-08](https://github.com/ZorinOS/zorin-desktop-themes/assets/102679854/5f866dcf-77e1-4088-b11e-2231c2029eb3)

toggle buttons are missplaced / not showing.

Also on gnome 45:

![Screenshot from 2023-11-20 13-40-28](https://github.com/ZorinOS/zorin-desktop-themes/assets/102679854/82bfcbb5-121f-49b8-89c2-ea765c5406aa)

The new activities button is still present, but i'm not sure your theme will cover this support.

**Comment by ArtyomZorin** [comment]
The current version of the Zorin themes are designed to work with the version of GNOME Shell (43) in the upcoming Zorin OS 17 release. As a result, the quick settings style for GNOME Shell 45 will not be implemented for the time being.
