### ISSUE TITLE
你们的主题我很喜欢,赞一个

### ISSUE THREAD

**Issue by 90du** [ZorinOS/zorin-desktop-themes#4]
你们的主题我很喜欢,赞一个，不过我不是很喜欢你们的标题栏按钮。我重新设计了他们，并制作了该主题的分支，看起来很不错，如果你们有兴趣可以合并到主题里面！我这里有个视频地址，你们有兴趣可以看看！

https://www.youtube.com/watch?v=Dq4cmG-7B4U&t=604s

**Comment by ArtyomZorin** [comment]
Thank you for your work! Unfortunately, as they don't alight with our internal design system and vision, we won't be merging your changes into the official Zorin theme.
We do, however, encourage you to maintain it as an unofficial third-party fork of our desktop theme.
