### ISSUE TITLE
Menu color issue

### ISSUE THREAD

**Issue by parmindersingh1** [ZorinOS/zorin-desktop-themes#5]
There is issue in colour of menu item ubuntu 19.10

Screenshots below

![Screenshot1](https://user-images.githubusercontent.com/3261782/69299471-9ffac300-0c36-11ea-9ccb-23b2f4150d03.png)
![Screenshot2](https://user-images.githubusercontent.com/3261782/69299472-a0935980-0c36-11ea-8ee5-e983b0e480e9.png)

**Comment by matfantinel** [comment]
This is happening on non-Zorin distros. I'm having the same issue on Pop_OS. The thing is that the styles for these specific menus are not set in Zorin theme, which makes them inherit from the default distro theme (Yaru Light for Ubuntu, Pop for Pop_OS, Adwaita for Fedora). 

I'm making a fork and will try to fix this - and possibly make a PR back here if the Zorin team is interested.

**Comment by matfantinel** [comment]
@parmindersingh1 check out my fork: https://github.com/matfantinel/zorin-desktop-themes

I have fixed the issues I've found on my Pop_OS installation. So far I've only fixed it in the blue themes (both Light and Dark). If you wanna try it out, feel free. Issues/PRs welcome on that repo too.

**Comment by parmindersingh1** [comment]
Thank you it is working on Ubuntu 19.10 as well
