### ISSUE TITLE
Gnome 3.36 Switch rendering issue

### ISSUE THREAD

**Issue by ohrie** [ZorinOS/zorin-desktop-themes#7]
On the new Gnome 3.36 there is a rendering issue, as shown in the picture, through all applications. 

![Bildschirmfoto von 2020-03-16 19-13-35](https://user-images.githubusercontent.com/6567206/76787990-5d975c00-67ba-11ea-9c19-6368ce4233e1.png)

**Comment by sleepforlife** [comment]
same here

**Comment by A-Hussein-M** [comment]
Same on Fedora with gnome 3.36.

**Comment by ArtyomZorin** [comment]
Thanks for the reports! The issue has now been fixed in the new 2.1.3 release.
