### ISSUE TITLE
Add support for GTK4

### ISSUE THREAD

**Issue by LinuxLlama** [ZorinOS/zorin-desktop-themes#8]
While Zorin OS itself may only ship GTK3 applications, the introduction of the Flathub repository is sure to bring an ugly mess. See the screenshot below. The main issue is the massive title bar, which is especially broken on GNOME Usage 3.38.1. There are also incidences where the theme draws borders where they shouldn't be. Again, see Usage.

![Screenshot from 2021-05-14 11-46-56](https://user-images.githubusercontent.com/29968331/118315555-855f7e00-b4aa-11eb-9a25-6f9e2a517f28.png)

**Comment by ArtyomZorin** [comment]
Based on your screenshot, it appears that issues primarily lied in how the viewswitcher buttons (in the windows' headerbars) were styled in the Zorin themes. In the latest update (version 3.3), we've added new styling code for these viewswitcher widgets that also corrects the height of the window's headerbars, as you can see in the screenshot below:
![Screenshot from 2021-05-30 21-08-07](https://user-images.githubusercontent.com/3945334/120118689-bd91dc80-c18b-11eb-8d4a-049550c394c2.png)
